# Generated by Django 3.0.8 on 2020-07-19 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_question_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
